core:
  workspace:
    dev: "[D] Fabric Autocreated Workspace 2"
    test: "[T] Fabric Autocreated Workspace 2"
    prod: "[P] Fabric Autocreated Workspace 2"
  
  repository_directory: "."  # Relative to config.yml location
  
  parameter: "parameter.yml"  # References existing parameter.yml

publish:
  skip:
    dev: false
    test: false
    prod: false

unpublish:
  skip:
    dev: false
    test: false
    prod: false

features:
  - enable_experimental_features
  - enable_config_deploy
  - enable_shortcut_publish
